management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true

  server:
    servlet:
      context-path: /